### ISSUE TITLE
Link Setup Frame Type - Undefined Bit?

### ISSUE THREAD

**Issue by lxmyers** [sp5wwp/M17_spec#1]
Hello,
         On Page 7 (PDF Page 11) under "Table 4: Bitfields of type field", Bit 1 is not defined. Just curious if this was an oversight or intentional?

Cheers, 
Alex.

P.S. Very impressive protocol, well done gents.

**Comment by sp5wwp** [comment]
Hey!
Thanks for your feedback. This is an oversight :-) We are going to fix it ASAP.

73,
Wojciech SP5WWP

**Comment by lxmyers** [comment]
Brilliant!

Again, very exciting project. Looking forward to seeing it progress.
Alex.

**Comment by sp5wwp** [comment]
You can also use IRC to communicate with us :-)
irc.geekshed.net - #M17

**Comment by sp5wwp** [comment]
Fixed.
